version: 0.1 # 임의의 버전 이름
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Create Profile
      - echo $Procfile > $CODEBUILD_SRC_DIR/Procfile
  # npm 명령어는 정적 파일 생성을 위해 package.json에 작성한 scripts에 맞게 작성합니다.
artifacts: # CodeBuild의 output artifacts를 지정합니다.
  files:
    - '**/*'
    - .next/**/*
    - locales/**/*
    - static/**/*
    - package.json
    - next.config.js
    - tsconfig.json
    - tsconfig.server.json
    - Procfile
    - 'node_modules/**/*'
  base-directory: '.next'   # next 디렉토리의 모든 파일이 해당됩니다.
