version: 0.2

phases:
  install:
    commands:
      - echo Installing dependency...
      - cd frontend
      - npm install
      - npm install -g next
      - npm install -g typescript
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
artifacts:
  files:
    - .next/**/*
    - locales/**/*
    - static/**/*
    - package.json
    - next.config.js
    - tsconfig.json
    - tsconfig.server.json
  base-directory: frontend
