server:
  port: ${SERVER_PORT}
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /docs
spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
