server:
  port: ${SERVER_PORT}
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /docs
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
